auth:
  rootUser: lakehouse_admin
  rootPassword: lakehouse_password

defaultBuckets: "lakehouse-data"

service:
  type: NodePort
  nodePorts:
    api: 30000
    console: 30001

persistence:
  size: 10Gi